server:
  port: 9002

spring:
  application:
    name: websocket
  cloud:
    nacos:
      discovery:
        #        注释掉解决控制台登陆失败问题
#        username: nacos
#        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public
        group: nacos

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/website?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1





definition:
    kafka: http://kafka







mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
  typeAliasesPackage: com.wangshuos.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    lazy-loading-enabled: true
  #    aggressive-lazy-loading: false
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)