server:
  port: 9004

spring:
  application:
    name: kafka
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
